// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqXg0RdLzRpMhweJl-750tQ0nvPPhEEc',
    appId: '1:150508276344:web:f73d32714f9ae854e2bb8d',
    messagingSenderId: '150508276344',
    projectId: 'ledgerl-e4673',
    authDomain: 'ledgerl-e4673.firebaseapp.com',
    storageBucket: 'ledgerl-e4673.appspot.com',
    measurementId: 'G-GTS7PRDBN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiM2hiFOvWCzggex0piousC57-vS7rBjg',
    appId: '1:150508276344:android:33b480fdb4b0a9cbe2bb8d',
    messagingSenderId: '150508276344',
    projectId: 'ledgerl-e4673',
    storageBucket: 'ledgerl-e4673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSW6Pm22iKbSn1FT6hpnQIbOtcgtOQDk',
    appId: '1:150508276344:ios:7e106afad5bacd6ce2bb8d',
    messagingSenderId: '150508276344',
    projectId: 'ledgerl-e4673',
    storageBucket: 'ledgerl-e4673.appspot.com',
    iosBundleId: 'com.lj.walletLj',
  );
}
